Vagrant.configure("2") do |config|
  config.vm.define "testing" do |testing|
    testing.vm.box = "generic/ubuntu2204"
    testing.vm.hostname = "Testing"
    testing.vm.network "private_network", ip: "192.168.56.12"
    testing.vm.network "public_network"
    
    testing.vm.provider "virtualbox" do |vb|
      vb.gui = true
      vb.memory = "4096"
      vb.cpus = "4"
    end
    
    testing.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update && sudo apt-get upgrade
      sudo apt-get install -y ssh wget net-tools curl unzip nmap
      sudo useradd -m -s /bin/bash -p "$(openssl passwd -1 js)" js
      sudo usermod -aG sudo js
    SHELL
  end
end

